### ISSUE TITLE
Ablage von UML-Diagrammen

### ISSUE THREAD

**Issue by johep-ITC** [ThorbenKonopka/Stundenplan#15]
Vorgeschlagen wäre ein neuer Branch `feature/umlDiagramme`, der das Verzeichnis `UML-Diagramme` einführt.

Dort sollen alle Quelldateien von Diagrammen aus UML-Modellierungssoftware abgelegt werden.

**Comment by ThorbenKonopka** [comment]
Das klingt ziemlich gut. Was für Dateien möchtest du da ablegen?
einfach die Dateien, die drawio braucht?
(Du hast zwar "Quelldateien von UML-Modellierungssoftware" geschrieben aber ich vermute, dass du damit nicht meinst, dass wir die wirkliche Software (drawio oder plantuml) hier ablegen)

**Comment by johep-ITC** [comment]
> Das klingt ziemlich gut. Was für Dateien möchtest du da ablegen? einfach die Dateien, die drawio braucht? (Du hast zwar "Quelldateien von UML-Modellierungssoftware" geschrieben aber ich vermute, dass du damit nicht meinst, dass wir die wirkliche Software (drawio oder plantuml) hier ablegen)

Genau, gemeint sind die Diagramm-Dateien von beispielsweise draw.io  oder UMLet, habe das im issue weiter ausformuliert
