### ISSUE TITLE
Anforderungsdokument

### ISSUE THREAD

**Issue by ThorbenKonopka** [ThorbenKonopka/Stundenplan#2]
# Es muss ein Anforderungsdokument erstellt werden.

Dafür müssen die folgenden Sachen erledigt werden:
- [x] Anforderungsdokument anlegen. 
- [x] Projektvision schreiben.
- [x] UseCase Diagramm erstellen. 
- [x] nichtfunktionale Anforderungen schreiben.
- [x] funktionale Anforderungen schreiben.
- [x] Alle Anforderungen Priorisieren
- [x] Für alle Anforderungen den Aufwand schätzen.

**Comment by johep-ITC** [comment]
#14 erfüllt Punkt "UseCase Diagramm erstellen"
