### ISSUE TITLE
Anforderungen nummerieren

### ISSUE THREAD

**Issue by ThorbenKonopka** [ThorbenKonopka/Stundenplan#29]
Wir müssen noch die Anforderungen durchnummerieren.

**Comment by johep-ITC** [comment]
Lösungsvorschlag: [LaTeX Counter](https://www.overleaf.com/learn/latex/Counters)

**Comment by ThorbenKonopka** [comment]
Wir müssen bei der Durchnummerierung gucken, wie wir die Anforderungen konsistent halten. Wir sollen ja jede Anforderungen priorisieren und den Aufwand für die Umsetzung schätzen. Wir müssen eigentlich nochmal an die Priorisierung und die Schätzung ran. 

Da ist die Frage, wie wir das ganze aufbauen wollen. Was ich ungerne hätte wäre, wenn wir die Anforderungen drei Mal schreiben und wir uns dann auf die Reihenfolge der Anforderungen verlassen müssen. Ich würde zuerst besprechen wollen, wie unsere Priorisierungen und Schätzungen aussehen sollen. Basierend darauf sollten wir eine Lösung für die Nummerierung finden.
