### ISSUE TITLE
Anforderungen für die Anwesenheitsliste

### ISSUE THREAD

**Issue by ThorbenKonopka** [ThorbenKonopka/Stundenplan#30]
Wir müssen noch die Anforderungen für die Anwesenheitsliste aus Sicht von Dozenten und Verwalter erheben.

**Comment by MasterMT9** [comment]
Ich würde meinen, dass ein Dozent nur während des Vorlesungszeitraums die Anwesenheit eintragen können sollte. Ein Verwalter sollte bei potentiellen Fehlern jedoch den Eintrag bearbeiten können. Wie stehst du dazu @ThorbenKonopka ?
