### ISSUE TITLE
Readme erweitern

### ISSUE THREAD

**Issue by ThorbenKonopka** [ThorbenKonopka/Stundenplan#5]
Die README.md muss so angepasst werden, dass entnehmbar ist, wie an dem Projekt gearbeitet wird. Dafür muss das Vorgehen mit den Forks und den PRs erläutert werden. Ziel ist es Personen, die weniger Erfahrung mit Git haben, mit dieser Doku soweit zu unterstützen, dass sie keine bzw. wenig Hilfe benötigen.

**Comment by MasterMT9** [comment]
Bin dabei.
